### ISSUE TITLE
Parametrise the installation

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#7]
**Is your feature request related to a problem? Please describe.**

When instanciating the stack, need a way to disable/enable services (e.g. use Superset and not Grafana, or both, or none, ...), maybe also provide custom configurations at the stack level (namespace, ...)

**Describe the solution you'd like**

A way to parametrise the stack: e.g. decide which services are active, add some configs, ...

**Describe alternatives you've considered**

Some ways to achieve that:

1. iterate on the [deploy.sh](helm/deploy.sh) to add shell parameters, and logic inside -> quick and dirty
2. translate deploy.sh into an Ansible script to be executed on the host. -> forces users to isntall ansible on top of helm and kubectl, adds a tech to the stack
3. use an Ansible pod to take care of the helm and kubectl stuff (maybe this would remove the dependency on the helm client and kubectl on the host system?) -> same as 2. above but removes the requirements to install Ansible 
4. leverage [Helm charts dependencies](https://github.com/helm/helm/blob/master/docs/helm/helm_dependency.md), maybe having one central "fadi" chart that references all the others -> this will not take care of the kubectl stuff, but  may be sufficient to provide modularity/parameters

**Additional context**

This would offer a nice way to provide examples (e.g. "minimal stack", or Tensorflow vs Spark stacks, ...

**Comment by alexnuttinck** [comment]
I think option 4 is the best option. Example with the elastick-stack: https://github.com/helm/charts/tree/master/stable/elastic-stack What do you think? Options to enable or disable components could be passed into the "values.json" file.

**Comment by alexnuttinck** [comment]
I have created this branch: https://github.com/cetic/fadi/tree/feature/fadi-helm-chart to make some tests and create a first draft of the fadi Helm Chart.

**Comment by alexnuttinck** [comment]
Ideas for the values.yaml of the future fadi Helm chart:

* each fadi component can be enabled/disabled into the values.json
* we can pass specific variables for components, see jupyterhub for instance.

I propose to use this centralized yaml file instead of using the current structure.

```yaml
---
# Default values for FADI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
spark:
  enabled: true

superset:
  enabled: true

postgresql:
  enabled: true

minio:
  enabled: true

grafana:
  enabled: true

jupyterhub:
  enabled: true
  proxy:
    secretToken: 'af83775ec3bfaf0507ce596df51d491e7ed54450adc454038fa7405495465f19'

nifi:
  enabled: true

pgadmin:
  enabled: true
```

What do you think?
